### ISSUE TITLE
Increase icon size.

### ISSUE THREAD

**Issue by Abhigyan103** [Abhigyan103/Clickboard#11]
Increase the icon size which is shown in the home screen for better viewing.

**Comment by skfareeduddin** [comment]
I'm unable to find the home screen. Can you tell me path?

**Comment by Abhigyan103** [comment]
> I'm unable to find the home screen. Can you tell me path?

This is refering to the icon for the app shown in the homescreen of the app drawer.

**Comment by sneha502** [comment]
I want to work on this issue. Please assign me.

**Comment by pranjalipilankar** [comment]
Hi @Abhigyan103, I want to contribute to this. Please assign me this issue for JWOC'24 :)

**Comment by shashank-lol** [comment]
I would like to work on this issue under JWOC

**Comment by prerna12s** [comment]
@Abhigyan103 please assign me this issue under JWOC

**Comment by shashank-lol** [comment]
Which icon size do i need to increase? the one showed on the splash screen?

**Comment by Abhigyan103** [comment]
No, the app icon in the launcher.

**Comment by Abhigyan103** [comment]
![logo_small](https://github.com/Abhigyan103/Clickboard/assets/91414842/0b306cc4-4e76-4d0b-a824-ffca156ec8c6)
