### ISSUE TITLE
Splash screen double icons.

### ISSUE THREAD

**Issue by Abhigyan103** [Abhigyan103/Clickboard#12]
Splash screen shows double icons on phones with older android version.
![Screenshot (229)](https://github.com/Abhigyan103/Clickboard/assets/91414842/8894f309-962e-4719-99e1-d7e371c44cda)

**Comment by Abhigyan103** [comment]
Is there any update ?

**Comment by Redvey** [comment]
I want to work on this

**Comment by Abhigyan103** [comment]
Any Update ?

**Comment by Redvey** [comment]
> Any Update ?

I didn't get time to work on it today, will make a PR by tomorrow
