### ISSUE TITLE
View Password

### ISSUE THREAD

**Issue by Abhigyan103** [Abhigyan103/Clickboard#14]
Add a password visibility eye icon in the login/signup page.
The visibility should last for 3-4 seconds before going back to obscured.

**Comment by AayushPaigwar** [comment]
Hello @Abhigyan103 
I am interested in doing this. Kindly assign me this issue :)

**Comment by pranjalipilankar** [comment]
Hi @Abhigyan103 
I am interested in doing this. I am familiar with the Flutter front-end framework and have made login/Sign-up pages with this feature before. Please assign me the issue :)

**Comment by prerna12s** [comment]
@Abhigyan103 Please assign this issue to me under JWOC
