### ISSUE TITLE
College website

### ISSUE THREAD

**Issue by Abhigyan103** [Abhigyan103/Clickboard#16]
Add an onTap feature to every instance of the college logo to make it redirect to the college website `https://jgec.ac.in/`

**Comment by Redvey** [comment]
Hello @Abhigyan103  Can I work on this issue?

**Comment by avirupnandi1** [comment]
Hello @Abhigyan103 , I have just added onTap functionality to the widget using InkWell. Also updated the pubspec.yaml file with the url_launcher dependency. Take a look!

**Comment by Redvey** [comment]
@Abhigyan103  While launching I am facing this issue: 
No application found for TargetPlatform.ios.
Is your project missing an ios/Runner/Info.plist?
Consider running "flutter create ." to create one.

**Comment by Redvey** [comment]
Hello @Abhigyan103 , please assign this to me.

**Comment by Redvey** [comment]
Hello @Abhigyan103 , please assign this to me.
