### ISSUE TITLE
Add google sign in

### ISSUE THREAD

**Issue by Abhigyan103** [Abhigyan103/Clickboard#20]
Add google sign in in the login page using firebase

**Comment by Astroxphiliauxx** [comment]
@Abhigyan103 Can you assign me this issue?

**Comment by Astroxphiliauxx** [comment]
@Abhigyan103 can you help me in arrangement of the file? I have made a dart file googleAuth.dart, where should i place it? 
Is authentication -> controllers a right place for it?

**Comment by Abhigyan103** [comment]
yeah sure!
