### ISSUE TITLE
Firebase : Change Password

### ISSUE THREAD

**Issue by Abhigyan103** [Abhigyan103/Clickboard#30]
**Is your feature request related to a problem? Please describe.**
Need to add a change password feature in the Account section

**Describe the solution you'd like**
The change password feature should ask for the new password and the old password in a snackbar, just like the delete account feature

**Comment by Astroxphiliauxx** [comment]
in this issue , user have to input the old and new password to reset, without being redirected?

**Comment by Abhigyan103** [comment]
Redirected to where ?

**Comment by Astroxphiliauxx** [comment]
there are two ways to implement change password:
1. using send email, which would redirect to change password
2. on screen change password by adding old and new password

which way do you want?

**Comment by Abhigyan103** [comment]
The second one

**Comment by Astroxphiliauxx** [comment]
ok assign me the issue @Abhigyan103

**Comment by Abhigyan103** [comment]
Any Update ?

**Comment by Astroxphiliauxx** [comment]
i m working on it !
