### ISSUE TITLE
Remove the green background from these icons

### ISSUE THREAD

**Issue by Abhigyan103** [Abhigyan103/Clickboard#31]
**Describe the bug**
There is an ugly looking green background in icons in the account section,.

**To Reproduce**
1. Go to 'Accounts'

**Expected behavior**
The icon should only be visible in white colour and not the background 

**Screenshots**
![Screenshot_20240116-015702_Clickboard.png](https://github.com/Abhigyan103/Clickboard/assets/91414842/20e79fa5-5279-4594-b9b5-1fb1d53354e0)

**Smartphone :**
 - Device: Redmi Note 9
 - OS: Android 13

**Comment by avirupnandi1** [comment]
Assign me the issue
