### ISSUE TITLE
Add Sign in with apple (Firebase)

### ISSUE THREAD

**Issue by Abhigyan103** [Abhigyan103/Clickboard#37]
**Is your feature request related to a problem? Please describe.**
Make a sign in with apple button just below sign in with apple.

**Describe the solution you'd like**
You should use Fontawesome icon and the google_sign_button widget.

**Comment by avirupnandi1** [comment]
Hi @Abhigyan103 , I can work on this issue, just let me confirm can I use sign_in_with_apple: ^5.0.0 package for this?

**Comment by Abhigyan103** [comment]
any update ?

**Comment by SharmaDhruv2511** [comment]
Working on it!

**Comment by SharmaDhruv2511** [comment]
Hi @Abhigyan103  can i do it on windows using firebase or mac is compulsory for apple authentication??

**Comment by Abhigyan103** [comment]
no it is not compulsory

**Comment by Abhigyan103** [comment]
??
