### ISSUE TITLE
Verify Email Shown for a split second

### ISSUE THREAD

**Issue by Abhigyan103** [Abhigyan103/Clickboard#39]
**Describe the bug**
There is verify email screen shown just after logging out for a split second.

**To Reproduce**
1. Go to `Account`
2. Click on `Log out`
4. See the verify email screen shown for a split second.

**Expected behavior**
The verify email screen should not be shown.

**Screenshots**

https://github.com/Abhigyan103/Clickboard/assets/91414842/f81e2a64-cc6e-4714-8ceb-c2403cb4500d

**Additional context**
The problem may be in the routing

**Comment by avirupnandi1** [comment]
Assign me..Wanna work on this issue
