### ISSUE TITLE
Delete Account Icon Chnage

### ISSUE THREAD

**Issue by Abhigyan103** [Abhigyan103/Clickboard#40]
**Describe the bug**
The icon for delete account is incorrect

**To Reproduce**
1. Go to `Account
4. See the `Delete Account` Option

**Expected behavior**
The `Delete Account` option should be a Dustbin icon ( Delete )

**Screenshots**
![WhatsApp Image 2024-01-17 at 22 38 20_82a969ba](https://github.com/Abhigyan103/Clickboard/assets/91414842/e974a06f-5067-43fe-9d2e-1a7f286dbab9)

**Comment by AnanyaSinghal23** [comment]
@Abhigyan103 I would like to fix the issue under JWOC
