### ISSUE TITLE
[Firestore Database] : Delete the Firestore document of the user

### ISSUE THREAD

**Issue by Abhigyan103** [Abhigyan103/Clickboard#51]
**Describe the bug**
The Firestore Database document of a user exists even after deleting the account.

**To Reproduce**
1. Go to `Account`
2. Click on `Delete Account`
3. Enter your Password
4. Go to the firebase console.
5. Check the firestore databse

**Expected behavior**
The document should be deleted on account deletion.

**Comment by AnanyaSinghal23** [comment]
@Abhigyan103 I would like to work on the issue under JWOC

**Comment by Abhigyan103** [comment]
Sorry, This issue was solved before, I just forgot.
