### ISSUE TITLE
[Google Sign in] : Delete Account

### ISSUE THREAD

**Issue by Abhigyan103** [Abhigyan103/Clickboard#52]
**Is your feature request related to a problem? Please describe.**
Add the support for delete account if user signed in using email and password and does not have a password.

**Comment by Abhigyan103** [comment]
You have to reauthenticate using google

**Comment by Astroxphiliauxx** [comment]
ok assign me this issue @Abhigyan103

**Comment by Abhigyan103** [comment]
Any update ?

**Comment by Astroxphiliauxx** [comment]
Though just been 1 day working, i had added the feature but after syncing through main upstream , i again got that error "Null check  contains a null value". So i m again reinstalling the project. And would update you soon.
