### ISSUE TITLE
[Bug] : Email Verification Alignment

### ISSUE THREAD

**Issue by Abhigyan103** [Abhigyan103/Clickboard#54]
**Describe the bug**
Very Email button has buggy text align.

**To Reproduce**
1. Go to `sign up`
2. Fill details and create a new account
3. See error

**Screenshots**
![Screenshot_20240118-185116_Clickboard](https://github.com/Abhigyan103/Clickboard/assets/91414842/e77cc6f6-c82f-4d95-9efc-bb043bb7107d)

**Comment by avirupnandi1** [comment]
assign me
