### ISSUE TITLE
[UI] : Design a documents page

### ISSUE THREAD

**Issue by Abhigyan103** [Abhigyan103/Clickboard#56]
**Is your feature request related to a problem? Please describe.**
Design a documents page UI in Figma and upload it in the assets folder.

**Describe the solution you'd like**
The Page should have a Floating action button to add/upload documents, thumbnails views of all documents with title

**Describe alternatives you've considered**
Here is a reference image :
![Document Reference](https://i.pinimg.com/736x/23/93/9c/23939c830802410d95b7be3aaeb30ed4.jpg)

**Comment by shashank-lol** [comment]
please assign this issue to me under jwoc

**Comment by Abhigyan103** [comment]
Any update ?
