### ISSUE TITLE
Unable to open account and result section 

### ISSUE THREAD

**Issue by Astroxphiliauxx** [Abhigyan103/Clickboard#59]
<h2> Describe the bug </h2>

<h2>To Reproduce</h2>

1. Login app
2. Click on account or result in bottom nav bar.
3. See error

<h2>Screenshots</h2>

<img width="204" alt="Screenshot 2024-01-20 204826" src="https://github.com/Abhigyan103/Clickboard/assets/118283802/300f78a9-d05e-469f-b17d-92186bb99ff5">
<img width="191" alt="Screenshot 2024-01-20 204838" src="https://github.com/Abhigyan103/Clickboard/assets/118283802/f4e6f9fd-212e-4fe8-a1cc-3cc8ec5538bf">

<h2>Smartphone :</h2>
- Device: Android Pixel 3A [api-34]

**Comment by Abhigyan103** [comment]
Please sync your code to the latest version

**Comment by Astroxphiliauxx** [comment]
I tried syncing by : git pull upstream main ,but it still isn't working

**Comment by Abhigyan103** [comment]
Did you try `git pull upstream main --force` ?

**Comment by Abhigyan103** [comment]
just sync the code in your fork and pull from that

**Comment by Astroxphiliauxx** [comment]
its still showing error

**Comment by Astroxphiliauxx** [comment]
is your's working?
